name: KLEE Test
on:
    push:
        branches: [ master ]
jobs:
    job_id:
        runs-on: ubuntu-latest
        container:
            image: klee/klee:2.1
            options: -u 0 --ulimit="stack=-1:-1"
        steps:
            - uses: actions/checkout@v2

            - name: Run in container
              run: |
                  echo This job does specify a container.
                  echo It runs in the container instead of the VM.

            - run: |
                  echo This is the second run step.
              name: Second step.

            - name: Create Build Environment
              run: cmake -E make_directory ${{ runner.workspace }}/build

            - name: Configure CMake
              shell: bash
              working-directory: ${{ runner.workspace }}/build
              run: |
                  cmake $GITHUB_WORKSPACE -G "Unix Makefiles"             \
                                          -D CMAKE_C_COMPILER=clang       \
                                          -D CMAKE_CXX_COMPILER=clang++   \
                                          -D CMAKE_BUILD_TYPE=Debug       \
                                          -D PSTORE_EXAMPLES=No           \
                                          -D PSTORE_EXCEPTIONS=No         \
                                          -D PSTORE_BITCODE=Yes           \
                                          -D PSTORE_DISABLE_UINT128_T=Yes


            - name: Build
              working-directory: ${{ runner.workspace }}/build
              shell: bash
              run: cmake --build . --target pstore-klee-run-all
