name: KLEE Test
on:
    push:
        branches: [ master ]
jobs:
    job_id:
        runs-on: ubuntu-latest
        container:
            image: klee/klee:2.1
            options: -u 0 --ulimit="stack=-1:-1"
        steps:
            - uses: actions/checkout@v2

            - name: Run in container
              run: |
                  echo This job does specify a container.
                  echo It runs in the container instead of the VM.

            - run: |
                  echo This is the second run step.
              name: Second step.
